/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import University.Persona.Student.PaymentRecord;
import University.Persona.Student.StudentProfile;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eve Dou
 */
public class FinancialManagementJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private StudentProfile studentProfile;
    
    public FinancialManagementJPanel(JPanel userProcessContainer, StudentProfile studentProfile) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.studentProfile = studentProfile;
        
        //初始化显示
        displayStudentFinancialInfo();
        populatePaymentHistory();
    }

    //构造显示账户余额方法
    private void displayStudentFinancialInfo(){
        //从studentProfile获取账户数据
        txtCurrentBalance.setText(String.format("$%.2f", studentProfile.getBalance()));//"$%.2f"→输出一个带美元符号的浮点数，保留两位小数
        txtOutstandingTuition.setText(String.format("$%.2f", studentProfile.getOutstandingTuition()));
        txtPaidAmount.setText(String.format("$%.2f",studentProfile.getPaidAmount()));
    }
    
    //显示缴费历史表格
    private void populatePaymentHistory(){
    DefaultTableModel model = (DefaultTableModel)tblPaymentHistory.getModel();
    model.setRowCount(0);//清空表格
    
    //从studentProfile获取付款记录
    for(PaymentRecord record: studentProfile.getPaymentHistory()){
        Object[]row = new Object[4];
        row[0] = record.getDate();
        row[1] = record.getNote();
        row[2] = record.getAmount();
        row[3] = record.getStatus();
        model.addRow(row);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFinancialManagement = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblAccountSummary = new javax.swing.JLabel();
        lblCurrentBalance = new javax.swing.JLabel();
        lblOutstandingTuition = new javax.swing.JLabel();
        lblPaidAmount = new javax.swing.JLabel();
        txtCurrentBalance = new javax.swing.JTextField();
        txtOutstandingTuition = new javax.swing.JTextField();
        txtPaidAmount = new javax.swing.JTextField();
        lblTuitionPayment = new javax.swing.JLabel();
        btnPayTuition = new javax.swing.JButton();
        btnRefundTuition = new javax.swing.JButton();
        btnViewTranscript = new javax.swing.JButton();
        lblPaymentHistory = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPaymentHistory = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 102, 255));

        lblFinancialManagement.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        lblFinancialManagement.setText("Financial Management");

        btnBack.setText("<<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblAccountSummary.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblAccountSummary.setText("Account Summary:");

        lblCurrentBalance.setText("Current Balance:");

        lblOutstandingTuition.setText("Outstanding Tuition:");

        lblPaidAmount.setText("Paid Amount:");

        txtCurrentBalance.setEditable(false);

        txtOutstandingTuition.setEditable(false);

        txtPaidAmount.setEditable(false);
        txtPaidAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaidAmountActionPerformed(evt);
            }
        });

        lblTuitionPayment.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblTuitionPayment.setText("Tuition Payment:");

        btnPayTuition.setText("Pay Tuition");
        btnPayTuition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayTuitionActionPerformed(evt);
            }
        });

        btnRefundTuition.setText("Refund Tuition");
        btnRefundTuition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefundTuitionActionPerformed(evt);
            }
        });

        btnViewTranscript.setText("View Transcript");
        btnViewTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTranscriptActionPerformed(evt);
            }
        });

        lblPaymentHistory.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblPaymentHistory.setText("Payment History:");

        tblPaymentHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Type", "Amount", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblPaymentHistory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(83, 83, 83)
                                .addComponent(lblFinancialManagement))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblCurrentBalance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblOutstandingTuition, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPaidAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCurrentBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOutstandingTuition, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPaidAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPaymentHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblTuitionPayment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAccountSummary, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPayTuition, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addComponent(btnRefundTuition, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(btnViewTranscript, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(lblFinancialManagement))
                .addGap(18, 18, 18)
                .addComponent(lblAccountSummary)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurrentBalance)
                    .addComponent(txtCurrentBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOutstandingTuition)
                    .addComponent(txtOutstandingTuition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPaidAmount)
                    .addComponent(txtPaidAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(lblTuitionPayment)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPayTuition)
                    .addComponent(btnViewTranscript)
                    .addComponent(btnRefundTuition))
                .addGap(48, 48, 48)
                .addComponent(lblPaymentHistory)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPaidAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaidAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaidAmountActionPerformed

    private void btnPayTuitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayTuitionActionPerformed
    //检查余额是否为0或负数
    if(studentProfile.getBalance() <= 0){
        JOptionPane.showMessageDialog(this, "No balance available to pay tuition.");
        return;
    }
    //弹出输入框让用户输入要支付的金额
    String input = JOptionPane.showInputDialog(this,"Enter amount to pay:");
    if(input == null || input.isEmpty())return;
    
    //先准备一个double变量,用于接收解析后的金额
    double payAmount = 0.0;
    try{
        payAmount = Double.parseDouble(input);//把输入的字符串转成数字
    }catch(NumberFormatException e){//转换失败就给出提示
        JOptionPane.showMessageDialog(this,"Please enter a valid number!");
        return;
    }
    
    //输入金额必须>0
    if(payAmount <= 0){
        JOptionPane.showMessageDialog(this,"Amount must be greater than 0!");
        return;
    }
    
    //检查余额是否足够支付
    if(studentProfile.getBalance() < payAmount){
        JOptionPane.showMessageDialog(this,"Insufficient Balance!");
        return;
    }
    
    //更新账户数据(余额/应缴/已缴)
    studentProfile.setBalance(studentProfile.getBalance()-payAmount);//余额=余额-支付额
    studentProfile.setPaidAmount(studentProfile.getPaidAmount()+payAmount);//已缴=已缴+支付额
    studentProfile.setOutstandingTuition(Math.max(0,studentProfile.getOutstandingTuition()-payAmount));//应缴=应缴-支付额（不可小于0）
    
    //新增一条缴费记录(日期,金额,备注类型,状态)
    studentProfile.addPaymentRecord(new PaymentRecord(new java.util.Date(), payAmount, "Tuition Payment", "Completed"));
    
    //刷新页面显示:上面三个文本框+下面的表格
    displayStudentFinancialInfo();//最新余额/应缴/已缴
    populatePaymentHistory();//最新记录填到JTabel
    
    //成功提示
    JOptionPane.showMessageDialog(this,"Payment successful!");
    
    
    
    }//GEN-LAST:event_btnPayTuitionActionPerformed

    private void btnRefundTuitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefundTuitionActionPerformed
           //让用户输入要退款的金额
        String input = JOptionPane.showInputDialog(this,"Enter refund amount:");
        //取消或空直接
        if(input == null || input.isEmpty())return;
        
        //准备接收金额
        double refundAmount = 0.0;
        try{
            refundAmount = Double.parseDouble(input);//把字符串转成double
        }catch(NumberFormatException e){//非法输入提示
            JOptionPane.showMessageDialog(this,"Please enter a valid number!");
            return;
        }
    
        //金额必须>0
        if(refundAmount <= 0){
            JOptionPane.showMessageDialog(this,"Amount must be greater than 0!");
            return;
        }
        //退款不能超过已缴金额
        if(studentProfile.getPaidAmount()<refundAmount){
            JOptionPane.showMessageDialog(this,"No enough paid tuition to refund!");
            return;
        }
        //更新账户
        studentProfile.setBalance(studentProfile.getBalance()+refundAmount);
        studentProfile.setPaidAmount(studentProfile.getPaidAmount()-refundAmount);
        studentProfile.setOutstandingTuition(studentProfile.getOutstandingTuition()+refundAmount);
        //追加一条退款历史记录
        studentProfile.addPaymentRecord(new PaymentRecord(new java.util.Date(),-refundAmount, "Tuition Refund", "Refunded"));
        
        //刷新显示
        displayStudentFinancialInfo();
        populatePaymentHistory();
        
        //成功提示
        JOptionPane.showMessageDialog(this,"Refund successful!");
          
        
    }//GEN-LAST:event_btnRefundTuitionActionPerformed

    private void btnViewTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTranscriptActionPerformed
        //如果学费未缴清→禁止查看成绩单
        if(studentProfile.getOutstandingTuition() >0){
            JOptionPane.showMessageDialog(this,"You can not view the transcript until all tuition is paid off.");
            return;
        }
        //学费已缴清→打开成绩单页面
        TranscriptReviewJPanel panel = new TranscriptReviewJPanel(userProcessContainer, studentProfile);
        userProcessContainer.add("TranscriptJPanel", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnViewTranscriptActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    userProcessContainer.remove(this);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPayTuition;
    private javax.swing.JButton btnRefundTuition;
    private javax.swing.JButton btnViewTranscript;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAccountSummary;
    private javax.swing.JLabel lblCurrentBalance;
    private javax.swing.JLabel lblFinancialManagement;
    private javax.swing.JLabel lblOutstandingTuition;
    private javax.swing.JLabel lblPaidAmount;
    private javax.swing.JLabel lblPaymentHistory;
    private javax.swing.JLabel lblTuitionPayment;
    private javax.swing.JTable tblPaymentHistory;
    private javax.swing.JTextField txtCurrentBalance;
    private javax.swing.JTextField txtOutstandingTuition;
    private javax.swing.JTextField txtPaidAmount;
    // End of variables declaration//GEN-END:variables
}
