/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import University.Business;
import University.Persona.Student.StudentProfile;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eve Dou
 */
public class GraduationAuditJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Business business;
    private StudentProfile studentProfile;
    
    public GraduationAuditJPanel(JPanel upc, Business b, StudentProfile sp) {
        initComponents();
        this.userProcessContainer = upc;
        this.business = b;
        this.studentProfile = sp;
        
        populateProgramInfo();
        populateCreditSummary();
        populateCourseTable();
        updateGraduationStatus();
    }

    //显示Program信息
    private void populateProgramInfo() {
    txtProgramName.setText("Information Systems, MS"); //项目名称
    txtRequiredCredits.setText("32"); //毕业总学分要求
    }
    
    //显示学分汇总
    private void populateCreditSummary() {
    int coreCredits = 4;        //核心课程（INFO5100）
    int electiveCredits = 8;    //已完成选修课学分
    int totalCredits = coreCredits + electiveCredits; //汇总学分
    
    txtCoreCourse.setText(String.valueOf(coreCredits));
    txtElectiveCredits.setText(String.valueOf(electiveCredits));
    txtTotalCredits.setText(String.valueOf(totalCredits));
}
    //填充课程表(编写默认数据)
    private void populateCourseTable() {
    DefaultTableModel model = (DefaultTableModel) tblCourseList.getModel();
    model.setRowCount(0);

    Object[][] mockCourses = {
        {"INFO5100", "Application Engineering & Development", 4, "Completed"},
        {"INFO5200", "Web Design", 4, "Completed"},
        {"INFO5300", "Algorithms", 4, "In Progress"},
        {"INFO5400", "Database Management", 4, "In Progress"},
        {"INFO5500", "Big Data Systems", 4, "Not Started"}
    };

    for (Object[] row : mockCourses) {
        model.addRow(row);
    }
}
    //判断是否达到毕业条件
    private void updateGraduationStatus() {
    try {
        int requiredCredits = Integer.parseInt(txtRequiredCredits.getText());
        int totalCredits = Integer.parseInt(txtTotalCredits.getText());

        if (totalCredits >= requiredCredits) {
            tarGraduationStatus.setText("Eligible for Graduation!\n Congratulations!");
        } else {
            int remaining = requiredCredits - totalCredits;
            tarGraduationStatus.setText(" In Progress — You need " + remaining + " more credits to graduate.");
        }
    } catch (NumberFormatException e) {
        tarGraduationStatus.setText("Error: Invalid credit information.");
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblGraduationAudit = new javax.swing.JLabel();
        lblCreditSummary = new javax.swing.JLabel();
        lblProgramName = new javax.swing.JLabel();
        lblRequiredCredits = new javax.swing.JLabel();
        txtProgramName = new javax.swing.JTextField();
        txtRequiredCredits = new javax.swing.JTextField();
        lblProgramInformation = new javax.swing.JLabel();
        lblCoreCourse = new javax.swing.JLabel();
        lblTotalCredits = new javax.swing.JLabel();
        lblElectiveCredits = new javax.swing.JLabel();
        txtCoreCourse = new javax.swing.JTextField();
        txtElectiveCredits = new javax.swing.JTextField();
        txtTotalCredits = new javax.swing.JTextField();
        lblGraduationStatus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourseList = new javax.swing.JTable();
        lblCourseList = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tarGraduationStatus = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(0, 102, 102));

        btnBack.setText("<<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblGraduationAudit.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        lblGraduationAudit.setText("Graduation Audit");

        lblCreditSummary.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblCreditSummary.setText("Credit Summary:");

        lblProgramName.setText("Program Name:");

        lblRequiredCredits.setText("Required Credits:");

        txtProgramName.setEditable(false);

        txtRequiredCredits.setEditable(false);

        lblProgramInformation.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblProgramInformation.setText("Program Information:");

        lblCoreCourse.setText("Core Course (INFO 5100):");

        lblTotalCredits.setText("Total Credits Completed:");

        lblElectiveCredits.setText("Elective Credits Completed:");

        txtCoreCourse.setEditable(false);

        txtElectiveCredits.setEditable(false);

        txtTotalCredits.setEditable(false);
        txtTotalCredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalCreditsActionPerformed(evt);
            }
        });

        lblGraduationStatus.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblGraduationStatus.setText("Graduation Status:");

        tblCourseList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course Number", "Course Name", "Credits", "Status"
            }
        ));
        tblCourseList.setEnabled(false);
        jScrollPane1.setViewportView(tblCourseList);

        lblCourseList.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblCourseList.setText("Course List:");

        tarGraduationStatus.setEditable(false);
        tarGraduationStatus.setColumns(20);
        tarGraduationStatus.setRows(5);
        jScrollPane2.setViewportView(tarGraduationStatus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGraduationStatus)
                            .addComponent(lblCourseList)
                            .addComponent(lblProgramInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblCoreCourse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTotalCredits, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblElectiveCredits, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCoreCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtElectiveCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTotalCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblCreditSummary)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtRequiredCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblProgramName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(63, 63, 63)
                                    .addComponent(txtProgramName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblRequiredCredits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(176, 176, 176)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(74, 74, 74)
                                .addComponent(lblGraduationAudit, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lblGraduationAudit))
                .addGap(27, 27, 27)
                .addComponent(lblProgramInformation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProgramName)
                    .addComponent(txtProgramName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRequiredCredits)
                    .addComponent(txtRequiredCredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(lblCreditSummary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCoreCourse)
                    .addComponent(txtCoreCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblElectiveCredits)
                    .addComponent(txtElectiveCredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalCredits)
                    .addComponent(txtTotalCredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblCourseList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblGraduationStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalCreditsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalCreditsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    userProcessContainer.remove(this);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCoreCourse;
    private javax.swing.JLabel lblCourseList;
    private javax.swing.JLabel lblCreditSummary;
    private javax.swing.JLabel lblElectiveCredits;
    private javax.swing.JLabel lblGraduationAudit;
    private javax.swing.JLabel lblGraduationStatus;
    private javax.swing.JLabel lblProgramInformation;
    private javax.swing.JLabel lblProgramName;
    private javax.swing.JLabel lblRequiredCredits;
    private javax.swing.JLabel lblTotalCredits;
    private javax.swing.JTextArea tarGraduationStatus;
    private javax.swing.JTable tblCourseList;
    private javax.swing.JTextField txtCoreCourse;
    private javax.swing.JTextField txtElectiveCredits;
    private javax.swing.JTextField txtProgramName;
    private javax.swing.JTextField txtRequiredCredits;
    private javax.swing.JTextField txtTotalCredits;
    // End of variables declaration//GEN-END:variables
}
