/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.FacultyRole;

import University.Business;
import University.CourseCatalog.Course;
import University.CourseSchedule.CourseOffer;
import University.CourseSchedule.CourseSchedule;
import University.Department.Department;
import University.Persona.Faculty.FacultyAssignment;
import University.Persona.Faculty.FacultyProfile;
import java.util.ArrayList;
import java.util.Set;
import javax.swing.JOptionPane;

import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author kal bugrara
 * @author Michael Hynes
 * Course Management
    ▪ View and update assigned course details (title, description, schedule, capacity).
    ▪ Upload or modify syllabus.
    ▪ Open or close course enrollment (before semester start)
 * 
 */
public class FacultyManageCoursesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    Department department;
    FacultyProfile facultyProfile;    
    String selectedCourseNumber;
    String selectedSchedule;
    int selectedRow;

    public FacultyManageCoursesJPanel(Business bz, FacultyProfile f, JPanel jp) {
        initComponents();   
        CardSequencePanel = jp;
        this.facultyProfile = f;       
        this.business = bz;             
        this.department = bz.getCollege().findDepartmentByFaculty(f);
        
        resetUpdateSection();
        populateCombobox();
        populateTable();
    }
   
    public void populateCombobox() { 
        //Get semesters
        Set<String> semesters = department.getAllSemesters();
        for (String semester : semesters) {
            cbSchedule.addItem(semester);
        }
    }
    
    public void populateTable() {        
        //Setup our table
        DefaultTableModel model = (DefaultTableModel)tblHeader.getModel();
        model.setRowCount(0);  
        
        //Hide the syllabus
        TableColumnModel tcm = tblHeader.getColumnModel(); 
        TableColumn column = tcm.getColumn(4);
        column.setMinWidth(0);
        column.setMaxWidth(0);
        column.setPreferredWidth(0);
        column.setWidth(0); 
               
        ArrayList<FacultyAssignment> assignments = this.facultyProfile.getFacultyassignments(); // <-- Direct Field Access
        for (FacultyAssignment fa : assignments) {
            CourseOffer co = fa.getCourseOffer();         
            Course c = co.getSubjectCourse();
            CourseSchedule cs = department.findCourseScheduleByCourseOffer(co);

            Object[] row = new Object[6]; 
            row[0] = co.getCourseNumber();                
            row[1] = c.getCourseName();

            row[2] = cs.getSemester();//semester;
            row[3] = String.valueOf(co.getSeatCount());
            row[4] = co.getSyllabus();
            row[5] = co.getEnrollmentOpen();
            
            model.addRow(row);                      
        } 
    }    
    
    public void resetUpdateSection() {
        // --- Labels ---
        lblCapacity.setVisible(false);
        lblEnrollment.setVisible(false);
        lblName.setVisible(false);
        lblNumber.setVisible(false);
        lblSchedule.setVisible(false);
        lblSyllabus.setVisible(false);
        
        // --- Radio Buttons & Buttons ---
        rbClosed.setVisible(false);
        rbOpen.setVisible(false);
        btnSave.setVisible(false);
        
        // --- Text Fields & Combo Boxes ---
        tbCapacity.setVisible(false);
        tbName.setVisible(false);
        tbNumber.setVisible(false);
        taSyllabus.setVisible(false);
        spSyllabus.setVisible(false);
        cbSchedule.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgEnrollment = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        OrderScroll1 = new javax.swing.JScrollPane();
        tblHeader = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblNumber = new javax.swing.JLabel();
        tbNumber = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        tbName = new javax.swing.JTextField();
        lblSchedule = new javax.swing.JLabel();
        lblCapacity = new javax.swing.JLabel();
        tbCapacity = new javax.swing.JTextField();
        lblSyllabus = new javax.swing.JLabel();
        spSyllabus = new javax.swing.JScrollPane();
        taSyllabus = new javax.swing.JTextArea();
        lblEnrollment = new javax.swing.JLabel();
        rbOpen = new javax.swing.JRadioButton();
        rbClosed = new javax.swing.JRadioButton();
        btnSave = new javax.swing.JButton();
        cbSchedule = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        lblTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitle.setText("Manage Courses");
        add(lblTitle);
        lblTitle.setBounds(21, 20, 370, 28);

        tblHeader.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Number/Title", "Name/Desc.", "Schedule", "Capacity", "Syllabus", "Enrollment Open?"
            }
        ));
        OrderScroll1.setViewportView(tblHeader);

        add(OrderScroll1);
        OrderScroll1.setBounds(20, 90, 590, 160);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(20, 260, 74, 23);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate);
        btnUpdate.setBounds(490, 260, 120, 23);

        lblNumber.setText("Number/Title");
        add(lblNumber);
        lblNumber.setBounds(20, 300, 80, 30);
        add(tbNumber);
        tbNumber.setBounds(100, 300, 170, 30);

        lblName.setText("Name/Desc.");
        add(lblName);
        lblName.setBounds(20, 340, 80, 30);
        add(tbName);
        tbName.setBounds(100, 340, 170, 30);

        lblSchedule.setText("Schedule");
        add(lblSchedule);
        lblSchedule.setBounds(20, 380, 80, 30);

        lblCapacity.setText("Capacity");
        add(lblCapacity);
        lblCapacity.setBounds(20, 420, 80, 30);
        add(tbCapacity);
        tbCapacity.setBounds(100, 420, 50, 30);

        lblSyllabus.setText("Syllabus");
        add(lblSyllabus);
        lblSyllabus.setBounds(290, 300, 50, 16);

        taSyllabus.setColumns(20);
        taSyllabus.setRows(5);
        spSyllabus.setViewportView(taSyllabus);

        add(spSyllabus);
        spSyllabus.setBounds(354, 296, 260, 100);

        lblEnrollment.setText("Enrollment");
        add(lblEnrollment);
        lblEnrollment.setBounds(290, 410, 60, 16);

        bgEnrollment.add(rbOpen);
        rbOpen.setText("Open");
        add(rbOpen);
        rbOpen.setBounds(360, 410, 70, 21);

        bgEnrollment.add(rbClosed);
        rbClosed.setText("Closed");
        add(rbClosed);
        rbClosed.setBounds(430, 410, 70, 21);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave);
        btnSave.setBounds(490, 440, 120, 23);

        cbSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbScheduleActionPerformed(evt);
            }
        });
        add(cbSchedule);
        cbSchedule.setBounds(100, 380, 100, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.removeAll();
        FacultyWorkAreaJPanel aos = new FacultyWorkAreaJPanel(business, facultyProfile, CardSequencePanel);
        CardSequencePanel.add("faculty", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:        
        selectedRow = tblHeader.getSelectedRow();
        
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Please select a course offer to update!", "Warning", JOptionPane.WARNING_MESSAGE);           
            return;
        }
        
        //AI generated to save me time
        // --- Labels ---
        lblCapacity.setVisible(true);
        lblEnrollment.setVisible(true);
        lblName.setVisible(true);
        lblNumber.setVisible(true);
        lblSchedule.setVisible(true);
        lblSyllabus.setVisible(true);

        // --- Radio Buttons & Buttons ---
        rbClosed.setVisible(true);
        rbOpen.setVisible(true);
        btnSave.setVisible(true);

        // --- Text Fields & Combo Boxes---
        tbCapacity.setVisible(true);
        tbName.setVisible(true);
        tbNumber.setVisible(true);
        taSyllabus.setVisible(true);
        spSyllabus.setVisible(true);
        cbSchedule.setVisible(true);

        //Get values from the slected row
        String courseNumber = tblHeader.getValueAt(selectedRow, 0).toString().trim();
        String courseName = tblHeader.getValueAt(selectedRow, 1).toString().trim();
        String schedule = tblHeader.getValueAt(selectedRow, 2).toString().trim();
        String capacity = tblHeader.getValueAt(selectedRow, 3).toString().trim();
        String syllabus = tblHeader.getValueAt(selectedRow, 4).toString().trim();
        String enrollmentOpen = tblHeader.getValueAt(selectedRow,5).toString().trim();
        //String courseOfferID = tblHeader.getValueAt(selectedRow, 6).toString();

        //Set Fields
        tbNumber.setText(courseNumber);
        tbName.setText(courseName);
        cbSchedule.setSelectedItem(schedule);
        tbCapacity.setText(capacity);
        taSyllabus.setText(syllabus);
        if (enrollmentOpen == "true") {
            rbOpen.setSelected(true);
        } else {
            rbClosed.setSelected(true);
        }

        //Save selected Course Number for update code
        selectedCourseNumber = courseNumber;
        selectedSchedule = schedule;

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (
            tbNumber.getText().isBlank() ||
            tbName.getText().isBlank() ||
            tbCapacity.getText().isBlank() 
        ) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields!", "Data Required", JOptionPane.ERROR_MESSAGE);
            return; 
        }        
        
        int capacity = 0;
        Boolean enrollmentOpen;
           
        String number = tbNumber.getText();        
        String name = tbName.getText();   
        String semester = cbSchedule.getSelectedItem().toString().trim();
        String syllabus = taSyllabus.getText();                
        if (rbOpen.isSelected()) {
            enrollmentOpen = true;
        } else {
            enrollmentOpen = false;
        }
        
        //Check datatypes
        try {
            capacity = Integer.parseInt(tbCapacity.getText().trim());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the Capacity.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Course c = department.getCourseCatalog().getCourseByNumber(selectedCourseNumber);  
        CourseOffer co = department.getCourseSchedule(selectedSchedule).getCourseOfferByNumber(selectedCourseNumber);
        int seats = 0;
        
        //See if they tried to reduce the capacity
        if (capacity < co.getSeatCount()) {
            JOptionPane.showMessageDialog(null, "You can not reduce capacity.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;          
        } else {
            seats = capacity - co.getSeatCount();
        }
        
        //Get the course schedule
        CourseSchedule cs = department.findCourseScheduleByCourseOffer(co);
        
        //Write data
        c.setCourseNumber(number);
        c.setCourseName(name);      
        co.setEnrollmentOpen(enrollmentOpen);
        co.setSyllabus(syllabus);  
        co.generateSeats(seats);
        cs.setSemester(semester); //MH - Need to fix how this is saved.
        
        //Reset everything
        JOptionPane.showMessageDialog(this, "Data has been updated!", "Data Saved", JOptionPane.INFORMATION_MESSAGE);
        resetUpdateSection();
        populateTable();
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cbScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbScheduleActionPerformed
        // TODO add your handling code here:
        //populateTable();
    }//GEN-LAST:event_cbScheduleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane OrderScroll1;
    private javax.swing.ButtonGroup bgEnrollment;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbSchedule;
    private javax.swing.JLabel lblCapacity;
    private javax.swing.JLabel lblEnrollment;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblSchedule;
    private javax.swing.JLabel lblSyllabus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton rbClosed;
    private javax.swing.JRadioButton rbOpen;
    private javax.swing.JScrollPane spSyllabus;
    private javax.swing.JTextArea taSyllabus;
    private javax.swing.JTextField tbCapacity;
    private javax.swing.JTextField tbName;
    private javax.swing.JTextField tbNumber;
    private javax.swing.JTable tblHeader;
    // End of variables declaration//GEN-END:variables

}
