/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.FacultyRole;

import University.Business;
import University.CourseCatalog.Course;
import University.CourseSchedule.CourseOffer;
import University.CourseSchedule.CourseSchedule;
import University.Department.Department;
import University.Persona.Faculty.FacultyAssignment;
import University.Persona.Faculty.FacultyProfile;
import java.util.ArrayList;

import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kal bugrara
 * @author Michael Hynes
 * Tuition/Enrollment Insight
    ▪ View total tuition collected from enrolled students in their courses
 * 
 */
public class FacultyTuitionInsightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    Department department;
    FacultyProfile facultyProfile;
    

    public FacultyTuitionInsightJPanel(Business bz, FacultyProfile f, JPanel jp) {
        initComponents();
        CardSequencePanel = jp;
        this.facultyProfile = f;       
        this.business = bz;
        this.department = bz.getCollege().findDepartmentByFaculty(f);

        populateTableHeader();        
    }

    public void populateTableHeader() {        
        //Setup our table
        DefaultTableModel model = (DefaultTableModel)tblHeader.getModel();
        model.setRowCount(0);
            
        //Get an arrey of Courses            
        ArrayList<FacultyAssignment> assignments = this.facultyProfile.getFacultyassignments(); 
        for (FacultyAssignment fa : assignments) {
            CourseOffer co = fa.getCourseOffer();         
            Course c = co.getSubjectCourse();
            CourseSchedule cs = department.findCourseScheduleByCourseOffer(co);         
                
            Object[] row = new Object[4];               

            row[0] = cs.getSemester(); //Semester 
            row[1] = co.getCourseNumber(); //Course
            row[2] = co.getEnrollmentCount(); //Enrollment Count
            //AI - Helped with formatting.
            row[3] = String.format("$%,d", (int)co.getTotalCourseRevenues()); //Tuition

            model.addRow(row);  
        } 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        OrderScroll1 = new javax.swing.JScrollPane();
        tblHeader = new javax.swing.JTable();
        Back = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        lblTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitle.setText("Tuition/Enrollment Insight");
        add(lblTitle);
        lblTitle.setBounds(21, 20, 370, 28);

        tblHeader.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Semester", "Course", "Enrollment", "Tuition"
            }
        ));
        OrderScroll1.setViewportView(tblHeader);

        add(OrderScroll1);
        OrderScroll1.setBounds(20, 90, 560, 160);

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back);
        Back.setBounds(20, 260, 74, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.removeAll();

        FacultyWorkAreaJPanel aos = new FacultyWorkAreaJPanel(business, facultyProfile, CardSequencePanel);

        CardSequencePanel.add("faculty", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_BackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JScrollPane OrderScroll1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblHeader;
    // End of variables declaration//GEN-END:variables

}
