/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.FacultyRole;

import UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp.*;
import University.Business;
import University.CourseCatalog.Course;
import University.CourseSchedule.CourseOffer;
import University.CourseSchedule.CourseSchedule;
import University.CourseSchedule.SeatAssignment;
import University.Department.Department;
import University.Persona.Faculty.FacultyProfile;
import University.Persona.Student.StudentDirectory;
import University.Persona.Student.StudentProfile;
import java.util.ArrayList;

import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author kal bugrara
 * @author Michael Hynes
 * Course Management
    ▪ View and update assigned course details (title, description, schedule, capacity).
    ▪ Upload or modify syllabus.
    ▪ Open or close course enrollment (before semester start)
 * 
 */
public class FacultyManageCoursesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;
    Business business;
    Department department;
    FacultyProfile faculty;
    //String semester = "Fall2020";

    public FacultyManageCoursesJPanel(Business bz, FacultyProfile f, JPanel jp) {
        initComponents();        
        CardSequencePanel = jp;
        this.business = bz;
        //this.department = ;
        this.faculty = f;
        //this.department = bz.
        
        populateCombobox();
        populateTable();
    }

    
    public void populateCombobox() {        
        //Get semesters
        cbSemesterSearch.addItem("Fall2020");
        cbSemesterSearch.setSelectedIndex(0);       
                
    }
    
    public void populateTable() {
        //GOAL: View and update assigned course details (title, description, schedule, capacity) 
        //Also, display info on syllabus & open/close course enrollment
        
        //Course - Course Offer, co.getCourseNumber()    
        //Title - 
        //Description - 
        //Schedlue -
        //Capacity - 
        //Syllabus -
        //Open/close course enrollment - 
        
        //Setup our table
        DefaultTableModel model = (DefaultTableModel)tblHeader.getModel();
        model.setRowCount(0);               
        
        //Get courses assigned to the faculty
        String semester = cbSemesterSearch.getSelectedItem().toString().trim();
        CourseSchedule courseSchedule = department.getCourseSchedule(semester);
        
        if (courseSchedule == null) {
            return;
        }
        
        for (CourseOffer co : courseSchedule.getSchedule()) {       
            FacultyProfile assignedFaculty = co.getFacultyProfile();  

            //Make sure the faculty matches
            if (assignedFaculty != null && assignedFaculty.equals(faculty)) {

                Object[] row = new Object[3];                
                row[0] = co.getCourseNumber();                

                model.addRow(row);                      
            }
        }                
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSemesterSearch = new javax.swing.JLabel();
        cbSemesterSearch = new javax.swing.JComboBox<>();
        lblCourseSearch = new javax.swing.JLabel();
        tbCourseSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        OrderScroll1 = new javax.swing.JScrollPane();
        tblHeader = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnOpenEnrollment = new javax.swing.JButton();
        btnCloseEnrollment = new javax.swing.JButton();
        btnUploadSyllabus = new javax.swing.JButton();
        btnDownloadSyllabus = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        lblTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitle.setText("Manage Courses");
        add(lblTitle);
        lblTitle.setBounds(21, 20, 370, 28);

        lblSemesterSearch.setText("Semester");
        add(lblSemesterSearch);
        lblSemesterSearch.setBounds(20, 60, 48, 16);

        cbSemesterSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSemesterSearchActionPerformed(evt);
            }
        });
        add(cbSemesterSearch);
        cbSemesterSearch.setBounds(70, 60, 72, 22);

        lblCourseSearch.setText("Course");
        add(lblCourseSearch);
        lblCourseSearch.setBounds(160, 60, 37, 16);
        add(tbCourseSearch);
        tbCourseSearch.setBounds(210, 60, 64, 22);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch);
        btnSearch.setBounds(460, 60, 120, 23);

        tblHeader.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Semester", "Course", "Title", "Description", "Schedule", "Capacity", "Syllabus?"
            }
        ));
        OrderScroll1.setViewportView(tblHeader);

        add(OrderScroll1);
        OrderScroll1.setBounds(20, 90, 560, 160);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(20, 260, 74, 23);

        btnOpenEnrollment.setText("Open Enrollment");
        btnOpenEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenEnrollmentActionPerformed(evt);
            }
        });
        add(btnOpenEnrollment);
        btnOpenEnrollment.setBounds(180, 260, 120, 23);

        btnCloseEnrollment.setText("Close Enrollment");
        btnCloseEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseEnrollmentActionPerformed(evt);
            }
        });
        add(btnCloseEnrollment);
        btnCloseEnrollment.setBounds(320, 260, 120, 23);

        btnUploadSyllabus.setText("Upload Syllabus");
        btnUploadSyllabus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadSyllabusActionPerformed(evt);
            }
        });
        add(btnUploadSyllabus);
        btnUploadSyllabus.setBounds(180, 300, 120, 23);

        btnDownloadSyllabus.setText("Download Syllabus");
        btnDownloadSyllabus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadSyllabusActionPerformed(evt);
            }
        });
        add(btnDownloadSyllabus);
        btnDownloadSyllabus.setBounds(320, 300, 120, 23);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave);
        btnSave.setBounds(460, 440, 120, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.removeAll();

        FacultyWorkAreaJPanel aos = new FacultyWorkAreaJPanel(business, faculty, CardSequencePanel);

        CardSequencePanel.add("faculty", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnOpenEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenEnrollmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpenEnrollmentActionPerformed

    private void cbSemesterSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSemesterSearchActionPerformed
        // TODO add your handling code here:
        //populateTable();
    }//GEN-LAST:event_cbSemesterSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCloseEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseEnrollmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseEnrollmentActionPerformed

    private void btnDownloadSyllabusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadSyllabusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDownloadSyllabusActionPerformed

    private void btnUploadSyllabusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadSyllabusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUploadSyllabusActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane OrderScroll1;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCloseEnrollment;
    private javax.swing.JButton btnDownloadSyllabus;
    private javax.swing.JButton btnOpenEnrollment;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUploadSyllabus;
    private javax.swing.JComboBox<String> cbSemesterSearch;
    private javax.swing.JLabel lblCourseSearch;
    private javax.swing.JLabel lblSemesterSearch;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField tbCourseSearch;
    private javax.swing.JTable tblHeader;
    // End of variables declaration//GEN-END:variables

}
