/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.RegistrarRole;

import University.CourseCatalog.Course;
import University.CourseSchedule.CourseOffer;
import University.CourseSchedule.CourseSchedule;
import University.Persona.Faculty.FacultyProfile;
import University.Persona.Registrar.RegistrarProfile;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jingyangwang
 */
public class AddCourseOfferJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddEditCourseOfferJPanel
     */
    
    JPanel CardSequencePanel;
    RegistrarProfile registrarProfile;
    
    public AddCourseOfferJPanel(JPanel CardSequencePanel,RegistrarProfile rp) {
        
        this.CardSequencePanel = CardSequencePanel;
        registrarProfile = rp;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblCourseNumber = new javax.swing.JLabel();
        lblCourseName = new javax.swing.JLabel();
        lblCredits = new javax.swing.JLabel();
        lblFacultyName = new javax.swing.JLabel();
        lblCapacity = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        fieldCourseNumber = new javax.swing.JTextField();
        fieldCourseName = new javax.swing.JTextField();
        fieldCredits = new javax.swing.JTextField();
        fieldCapacity = new javax.swing.JTextField();
        comboFaculty = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        comboSemester = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(153, 153, 153));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        lblTitle.setText("Add New Course Offer");

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblCourseNumber.setText("Course Number");

        lblCourseName.setText("Course Name");

        lblCredits.setText("Credits");

        lblFacultyName.setText("Faculty Name");

        lblCapacity.setText("Capacity");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        comboFaculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gina Montana", "Joshua Miller", "Megan Anderson", "Sarah Wilson", "Michael Brown", "Jessica Davis", "Laura Garcia", "Jay Chou" }));

        jLabel1.setText("Semester");

        comboSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fall2020", "Spring2021", "Fall2021", "Spring2022" }));
        comboSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSemesterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCourseNumber)
                                .addComponent(lblCourseName)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCredits)
                                    .addComponent(lblFacultyName)
                                    .addComponent(lblCapacity))))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSave)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fieldCourseNumber)
                                .addComponent(fieldCourseName)
                                .addComponent(fieldCredits)
                                .addComponent(fieldCapacity)
                                .addComponent(comboFaculty, 0, 223, Short.MAX_VALUE)
                                .addComponent(comboSemester, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(lblTitle)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseNumber)
                    .addComponent(fieldCourseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseName)
                    .addComponent(fieldCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCredits)
                    .addComponent(fieldCredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFacultyName)
                    .addComponent(comboFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCapacity)
                    .addComponent(fieldCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(btnSave)
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        //remove current jpanel
        CardSequencePanel.remove(this);
        
        CardLayout layout = (CardLayout)CardSequencePanel.getLayout();
        //display the previous one
        layout.previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
                                           
    //collect information from fields
    String semester = (String)comboSemester.getSelectedItem();
    String courseNumber = fieldCourseNumber.getText();
    String courseName = fieldCourseName.getText();
    String facultyName = (String)comboFaculty.getSelectedItem();
    int credits;
    int numberOfSeat;

    //check if fields are empty
    if(courseNumber.isBlank() || courseName.isBlank() || facultyName.isBlank()) {
        JOptionPane.showMessageDialog(null, "All fields are mandatory","Warning",JOptionPane.WARNING_MESSAGE);
        return;
    }

    //check the number if rights
    try{
       credits = Integer.parseInt(fieldCredits.getText());
       numberOfSeat = Integer.parseInt(fieldCapacity.getText()); 
    } catch(Exception e){
        JOptionPane.showMessageDialog(null, "Please enter valid numbers for Credits and Capacity","Warning",JOptionPane.WARNING_MESSAGE);
        return;
    }

    //Create course and courseOffer
    Course course = new Course(courseName, courseNumber, credits);
    CourseOffer courseOffer = new CourseOffer(course);
    
    //Generate seats
    courseOffer.generateSeats(numberOfSeat); 

    //Assign teacher
    FacultyProfile selectedFaculty = null;
    for (FacultyProfile fp : registrarProfile.getDepartment().getFacultyDirectory().getTeacherList()) {
        if (fp.getPerson().getPersonId().equalsIgnoreCase(facultyName)) {
            selectedFaculty = fp;
            break;
        }
    }
    if (selectedFaculty != null) {
        courseOffer.AssignAsTeacher(selectedFaculty);
    } 

    //add course offer into course schedule
    CourseSchedule cs = registrarProfile.getDepartment().getCourseSchedule(semester);
    if (cs != null) {
        cs.getSchedule().add(courseOffer);
    }

    //pop-up successful message
    JOptionPane.showMessageDialog(null, "New Course Offer saved!","Successfully",JOptionPane.INFORMATION_MESSAGE);
    
    //clear all text filled
    fieldCourseNumber.setText("");
    fieldCourseName.setText("");
    fieldCredits.setText("");
    fieldCapacity.setText("");
    comboFaculty.setSelectedIndex(0);
    
    }//GEN-LAST:event_btnSaveActionPerformed

    private void comboSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSemesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSemesterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboFaculty;
    private javax.swing.JComboBox<String> comboSemester;
    private javax.swing.JTextField fieldCapacity;
    private javax.swing.JTextField fieldCourseName;
    private javax.swing.JTextField fieldCourseNumber;
    private javax.swing.JTextField fieldCredits;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCapacity;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblCourseNumber;
    private javax.swing.JLabel lblCredits;
    private javax.swing.JLabel lblFacultyName;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

        
   
}
