/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import University.CourseCatalog.Course;
import University.CourseCatalog.CourseCatalog;
import University.CourseSchedule.CourseOffer;
import University.Department.Department;
import University.Persona.Student.StudentProfile;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eve Dou
 */
public class CourseRegistrationJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private StudentProfile studentProfile;
    private Department department;
    private String searchType = "CourseNumber";
    
    public CourseRegistrationJPanel(JPanel userProcessContainer, StudentProfile studentProfile, Department department) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.studentProfile = studentProfile;
        this.department = department;
        
        populateAvailableCoursesTable(department.getAllCourseOffers());
        populateRegisteredCoursesTable(studentProfile.getCourseList());
    }

    //显示可选课程
    private void populateAvailableCoursesTable(ArrayList<CourseOffer>courseList){
        DefaultTableModel model = (DefaultTableModel)tblCourseOffer.getModel();
        model.setRowCount(0);//把表格行数设置为0，清空所有行。
        //把courseList里的每一门课，转成JTable的一行，并放进表格里。
        for (CourseOffer c : courseList){
            Object[] row = new Object[4];
            row[0] = c.getCourseNumber();
            row[1] = c.getSubjectCourse().getCourseName();
            row[2] = c.getFacultyProfile();
            row[3] = c.getCreditHours();
            
            model.addRow(row);
        }
    }
        
    //显示已注册课程
    private void populateRegisteredCoursesTable(ArrayList<CourseOffer>registeredCourses){
        DefaultTableModel model = (DefaultTableModel)tblRegisteredCourse.getModel();
        model.setRowCount(0);
        for(CourseOffer c : registeredCourses){
            Object[] row = new Object[4];
            row[0] = c.getCourseNumber();
            row[1] = c.getSubjectCourse().getCourseName();
            row[2] = c.getFacultyProfile();
            row[3] = c.getCreditHours();
            
            model.addRow(row);
        }
    }
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCourseRegistration = new javax.swing.JLabel();
        lblSearchBy = new javax.swing.JLabel();
        btnCourseNumber = new javax.swing.JButton();
        btnCourseName = new javax.swing.JButton();
        btnInstructor = new javax.swing.JButton();
        lblKeyword = new javax.swing.JLabel();
        txtKeyword = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourseOffer = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        lblCourseOffer = new javax.swing.JLabel();
        btnEnroll = new javax.swing.JButton();
        btnDrop = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRegisteredCourse = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 0, 0));

        lblCourseRegistration.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        lblCourseRegistration.setText("Course Registration");

        lblSearchBy.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblSearchBy.setText("Search By:");

        btnCourseNumber.setText("By CourseNumber");
        btnCourseNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseNumberActionPerformed(evt);
            }
        });

        btnCourseName.setText("By CourseName");
        btnCourseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseNameActionPerformed(evt);
            }
        });

        btnInstructor.setText("By Instructor");
        btnInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstructorActionPerformed(evt);
            }
        });

        lblKeyword.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblKeyword.setText("Keyword:");

        tblCourseOffer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CourseNumber", "CourseName", "Instructor", "Credits"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCourseOffer);

        btnBack.setText("<<<Back");

        lblCourseOffer.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblCourseOffer.setText("Available Course Offer:");

        btnEnroll.setText("Enroll");

        btnDrop.setText("Drop");

        tblRegisteredCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CourseNumber", "CourseName", "Instructor", "Credits"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblRegisteredCourse);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel1.setText("Registered Courses:");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnBack)
                        .addGap(107, 107, 107)
                        .addComponent(lblCourseRegistration))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCourseOffer)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEnroll, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDrop, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblKeyword)
                                    .addComponent(lblSearchBy))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtKeyword)
                                    .addComponent(btnCourseNumber))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCourseName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(btnInstructor)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseRegistration)
                    .addComponent(btnBack))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSearchBy)
                        .addGap(20, 20, 20)
                        .addComponent(lblKeyword))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCourseNumber)
                            .addComponent(btnCourseName)
                            .addComponent(btnInstructor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch))))
                .addGap(45, 45, 45)
                .addComponent(lblCourseOffer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEnroll)
                        .addGap(64, 64, 64)))
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(btnDrop)
                        .addGap(111, 111, 111))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCourseNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseNumberActionPerformed
        searchType = "CourseNumber";
    }//GEN-LAST:event_btnCourseNumberActionPerformed

    private void btnCourseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseNameActionPerformed
        searchType = "CourseName";
    }//GEN-LAST:event_btnCourseNameActionPerformed

    private void btnInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstructorActionPerformed
        searchType = "Instructor";
    }//GEN-LAST:event_btnInstructorActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String keyword = txtKeyword.getText();//读取输入框关键字
        ArrayList<CourseOffer>resultList = new ArrayList<>();//创建一个空的ArrayList，用来存放符合条件的搜索结果
    
        //遍历系统中所有课程
        for(CourseOffer c : department.getAllCourseOffers()){
        //提前把每门课的基本信息取出来放到变量中，方便后面判断
        String courseNumber = c.getCourseNumber();
        String courseName = c.getSubjectCourse().getCourseName();
        String instructor = c.getFacultyProfile().getPerson().getName();
        
        //根据searchType不同来匹配
        if(searchType.equals("CourseNumber") && courseNumber.toLowerCase().contains(keyword.toLowerCase())){
            resultList.add(c);
        }
        else if(searchType.equals("CourseName") && courseName.toLowerCase().contains(keyword.toLowerCase())){
            resultList.add(c);
        }
        else if(searchType.equals("Instructor") && instructor.toLowerCase().contains(keyword.toLowerCase())){
            resultList.add(c);
        }
    }
        //把搜索到的课程显示到表格中
        populateAvailableCoursesTable(resultList);
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCourseName;
    private javax.swing.JButton btnCourseNumber;
    private javax.swing.JButton btnDrop;
    private javax.swing.JButton btnEnroll;
    private javax.swing.JButton btnInstructor;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCourseOffer;
    private javax.swing.JLabel lblCourseRegistration;
    private javax.swing.JLabel lblKeyword;
    private javax.swing.JLabel lblSearchBy;
    private javax.swing.JTable tblCourseOffer;
    private javax.swing.JTable tblRegisteredCourse;
    private javax.swing.JTextField txtKeyword;
    // End of variables declaration//GEN-END:variables
}
