/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import University.Business;
import University.Persona.Student.StudentProfile;
import java.awt.CardLayout;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eve Dou
 */
public class CourseWorkManagementJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Business business;
    private StudentProfile studentProfile;
    private File selectedFile;
    
    public CourseWorkManagementJPanel(JPanel upc, Business b, StudentProfile sp) {
        initComponents();
        this.userProcessContainer = upc;
        this.business = b;
        this.studentProfile = sp;
      
        populateComboBox();
        populateProgress();
        populateTable();
    }
    
    //初始化表格***待补充
    private void populateTable() {
    DefaultTableModel model = (DefaultTableModel) tblAssignments.getModel();
    model.setRowCount(0);

    for (var cl : studentProfile.getTranscript().getAllCourseLoads()) {
        for (var sa : cl.getSeatAssignments()) {
            Object[] row = new Object[4];
            row[0] = sa.getCourseOffer().getCourseNumber(); //课程编号
            row[1] = sa.getAssignmentName();//作业名称
            row[2] = sa.getStatus();//状态
            row[3] = sa.getAssignmentScore(); //成绩

            model.addRow(row);
        }
    }
}
    //从学生的选课CourseLoad→SeatAssignment里，读取所有课程，显示在下拉菜单
    private void populateComboBox() {
    cmbCourse.removeAllItems();
    //从学生的成绩单transcript中获取所有课程
    for (var cl : studentProfile.getTranscript().getAllCourseLoads()) {
        for (var sa : cl.getSeatAssignments()) {
            String courseNumber = sa.getCourseOffer().getCourseNumber();
            cmbCourse.addItem(courseNumber);
        }
    }
    }
    
    //显示学生的GPA、已完成学分、通过率、学术状态。
    private void populateProgress() {
    double totalPoints = 0.0;
    int totalCredits = 0;
    int passedCourses = 0;
    int totalCourses = 0;

    for (var cl : studentProfile.getTranscript().getAllCourseLoads()) {
        for (var sa : cl.getSeatAssignments()) {
            totalCredits += sa.getCreditHours();
            totalPoints += sa.getGrade() * sa.getCreditHours();
            totalCourses++;
            if (sa.getGrade() >= 2.0) passedCourses++; // 假设2.0以上算通过
        }
    }

    double gpa = totalCredits > 0 ? totalPoints / totalCredits : 0.0;
    double completionRate = totalCourses > 0 ? (double) passedCourses / totalCourses * 100 : 0.0;

    txtTermGPA.setText(String.format("%.2f", gpa));
    txtCreditsCompleted.setText(String.valueOf(totalCredits));
    txtCompletionRate.setText(String.format("%.1f%%", completionRate));

    if (gpa >= 3.7) txtAcademicStanding.setText("Excellent");
    else if (gpa >= 3.0) txtAcademicStanding.setText("Good");
    else if (gpa >= 2.0) txtAcademicStanding.setText("Average");
    else txtAcademicStanding.setText("Probation");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblAssignmentSubmission = new javax.swing.JLabel();
        cmbCourse = new javax.swing.JComboBox<>();
        btnChooseFile = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        lblSubmittedAssignments = new javax.swing.JLabel();
        lblAcademicProgress = new javax.swing.JLabel();
        lblTermGPA = new javax.swing.JLabel();
        lblCreditsCompleted = new javax.swing.JLabel();
        lblCompletionRate = new javax.swing.JLabel();
        lblAcademicStanding = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAssignments = new javax.swing.JTable();
        txtCreditsCompleted = new javax.swing.JTextField();
        txtTermGPA = new javax.swing.JTextField();
        txtCompletionRate = new javax.swing.JTextField();
        txtAcademicStanding = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 102, 255));
        setForeground(new java.awt.Color(242, 242, 242));

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        lblTitle.setText("Coursework Management");

        btnBack.setText("<<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblAssignmentSubmission.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblAssignmentSubmission.setText("Assignment submission:");

        cmbCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnChooseFile.setText("Choose File");
        btnChooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseFileActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblSubmittedAssignments.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblSubmittedAssignments.setText("Submitted Assignments:");

        lblAcademicProgress.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblAcademicProgress.setText("Academic Progress:");

        lblTermGPA.setText("Term GPA:");

        lblCreditsCompleted.setText("Credits Completed:");

        lblCompletionRate.setText("Completion Rate:");

        lblAcademicStanding.setText("Academic Standing:");

        tblAssignments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CourseNumber", "Assignment", "Status", "Grade"
            }
        ));
        jScrollPane1.setViewportView(tblAssignments);

        txtCreditsCompleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreditsCompletedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(59, 59, 59)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmbCourse, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAssignmentSubmission, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSubmittedAssignments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addComponent(btnChooseFile, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblTermGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTermGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblAcademicProgress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAcademicStanding, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCompletionRate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCreditsCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtCreditsCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCompletionRate, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAcademicStanding, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addComponent(lblAssignmentSubmission)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChooseFile)
                    .addComponent(btnSubmit))
                .addGap(34, 34, 34)
                .addComponent(lblSubmittedAssignments)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblAcademicProgress)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTermGPA)
                    .addComponent(txtTermGPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreditsCompleted)
                    .addComponent(txtCreditsCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCompletionRate)
                    .addComponent(txtCompletionRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcademicStanding)
                    .addComponent(txtAcademicStanding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCreditsCompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreditsCompletedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreditsCompletedActionPerformed

    private void btnChooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseFileActionPerformed
    JFileChooser fileChooser = new JFileChooser();
    int returnValue = fileChooser.showOpenDialog(null);
    if (returnValue == JFileChooser.APPROVE_OPTION) {
        selectedFile = fileChooser.getSelectedFile();
        JOptionPane.showMessageDialog(this, "File Selected: " + selectedFile.getName());
    }

    }//GEN-LAST:event_btnChooseFileActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
       if (selectedFile == null) {
        JOptionPane.showMessageDialog(this, "Please choose a file first.");
        return;
    }
    
    String selectedCourseNumber = (String) cmbCourse.getSelectedItem();
    if (selectedCourseNumber == null) {
        JOptionPane.showMessageDialog(this, "Please select a course.");
        return;
    }
    
    // 直接从文件名创建作业名称（去掉扩展名）
    String fileName = selectedFile.getName();
    String assignmentName = fileName.contains(".") ? 
        fileName.substring(0, fileName.lastIndexOf('.')) : fileName;
    
    // 直接在表格中添加新行
    DefaultTableModel model = (DefaultTableModel) tblAssignments.getModel();
    Object[] newRow = new Object[4];
    newRow[0] = selectedCourseNumber;
    newRow[1] = assignmentName;
    newRow[2] = "Submitted";
    newRow[3] = "0.0"; // 等待评分
    
    model.addRow(newRow);
    
    JOptionPane.showMessageDialog(this, "Assignment submitted for " + selectedCourseNumber + "!");
    selectedFile = null; // 重置文件选择
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    userProcessContainer.remove(this);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChooseFile;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cmbCourse;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAcademicProgress;
    private javax.swing.JLabel lblAcademicStanding;
    private javax.swing.JLabel lblAssignmentSubmission;
    private javax.swing.JLabel lblCompletionRate;
    private javax.swing.JLabel lblCreditsCompleted;
    private javax.swing.JLabel lblSubmittedAssignments;
    private javax.swing.JLabel lblTermGPA;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblAssignments;
    private javax.swing.JTextField txtAcademicStanding;
    private javax.swing.JTextField txtCompletionRate;
    private javax.swing.JTextField txtCreditsCompleted;
    private javax.swing.JTextField txtTermGPA;
    // End of variables declaration//GEN-END:variables
}
