/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import University.CourseCatalog.Course;
import University.CourseCatalog.CourseCatalog;
import University.CourseSchedule.CourseOffer;
import University.Department.Department;
import University.Persona.Student.StudentProfile;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eve Dou
 */
public class CourseRegistrationJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private StudentProfile studentProfile;
    private Department department;
    private String searchType = "CourseNumber";
    
    public CourseRegistrationJPanel(JPanel userProcessContainer, StudentProfile studentProfile, Department department) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.studentProfile = studentProfile;
        this.department = department;
        
        tblCourseOffer.getTableHeader().setReorderingAllowed(false);
        tblRegisteredCourse.getTableHeader().setReorderingAllowed(false);

        populateAvailableCoursesTable(department.getAllCourseOffers());
        populateRegisteredCoursesTable();
    }

    //显示可选课程
    private void populateAvailableCoursesTable(ArrayList<CourseOffer> courseList) {
    DefaultTableModel model = (DefaultTableModel) tblCourseOffer.getModel();
    model.setRowCount(0);

    for (CourseOffer c : courseList) {
        Object[] row = new Object[4];
        row[0] = c.getCourseNumber();                    // 课程编号 → 第0列
        row[1] = c.getSubjectCourse().getCourseName();   // 课程名称 → 第1列
        row[2] = getInstructorByCourseNumber(c.getCourseNumber()); // 教师姓名
        row[3] = c.getCreditHours();                     // 学分
        model.addRow(row);
    }
}
        
    //显示已注册课程
    private void populateRegisteredCoursesTable() {
    DefaultTableModel model = (DefaultTableModel) tblRegisteredCourse.getModel();
    model.setRowCount(0);

    if (studentProfile.getRegisteredCourseOffers() != null) {
        for (CourseOffer c : studentProfile.getRegisteredCourseOffers()) {
            Object[] row = new Object[4];
            row[0] = c.getCourseNumber();                    // 课程编号 → 第0列
            row[1] = c.getSubjectCourse().getCourseName();   // 课程名称 → 第1列
            row[2] = getInstructorByCourseNumber(c.getCourseNumber());
            row[3] = c.getCreditHours();
            model.addRow(row);
        }
    }
}
    
        //计算当前已注册课程的总学分
       private int calculateTotalCredits() {
           int totalCredits = 0;

           // 直接从表格计算，而不是从 studentProfile
           DefaultTableModel model = (DefaultTableModel) tblRegisteredCourse.getModel();
           for (int i = 0; i < model.getRowCount(); i++) {
               int credits = (Integer) model.getValueAt(i, 3); // 第3列是学分
               totalCredits += credits;
           }

           return totalCredits;
       }
    
        //教师分配方法
        private String getInstructorByCourseNumber(String courseNumber) {
        if (courseNumber == null) return "None";
        String n = courseNumber.trim();
        if (n.equalsIgnoreCase("INFO5100")) return "Dr. Smith";
        if (n.equalsIgnoreCase("INFO5200")) return "Prof. Johnson";
        if (n.equalsIgnoreCase("INFO5300")) return "Dr. Williams";
        if (n.equalsIgnoreCase("INFO5400")) return "Prof. Brown";
        if (n.equalsIgnoreCase("INFO5500")) return "Dr. Davis";
        if (n.equalsIgnoreCase("INFO6205")) return "Dr. Taylor";
        if (n.equalsIgnoreCase("INFO6210")) return "Prof. Allen";
        if (n.equalsIgnoreCase("INFO6215")) return "Dr. Parker";
        if (n.equalsIgnoreCase("INFO7370")) return "Dr. Rae";
        return "Dr.Sandy";
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCourseRegistration = new javax.swing.JLabel();
        lblSearchBy = new javax.swing.JLabel();
        btnCourseNumber = new javax.swing.JButton();
        btnCourseName = new javax.swing.JButton();
        btnInstructor = new javax.swing.JButton();
        lblKeyword = new javax.swing.JLabel();
        txtKeyword = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourseOffer = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        lblCourseOffer = new javax.swing.JLabel();
        btnEnroll = new javax.swing.JButton();
        btnDrop = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRegisteredCourse = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 0, 0));

        lblCourseRegistration.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        lblCourseRegistration.setText("Course Registration");

        lblSearchBy.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblSearchBy.setText("Search By:");

        btnCourseNumber.setText("By CourseNumber");
        btnCourseNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseNumberActionPerformed(evt);
            }
        });

        btnCourseName.setText("By CourseName");
        btnCourseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseNameActionPerformed(evt);
            }
        });

        btnInstructor.setText("By Instructor");
        btnInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstructorActionPerformed(evt);
            }
        });

        lblKeyword.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblKeyword.setText("Keyword:");

        tblCourseOffer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CourseNumber", "CourseName", "Instructor", "Credits"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCourseOffer);

        btnBack.setText("<<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblCourseOffer.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblCourseOffer.setText("Available Course Offer:");

        btnEnroll.setText("Enroll");
        btnEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollActionPerformed(evt);
            }
        });

        btnDrop.setText("Drop");
        btnDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDropActionPerformed(evt);
            }
        });

        tblRegisteredCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CourseNumber", "CourseName", "Instructor", "Credits"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblRegisteredCourse);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel1.setText("Registered Courses:");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnBack)
                        .addGap(107, 107, 107)
                        .addComponent(lblCourseRegistration))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCourseOffer)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEnroll, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDrop, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblKeyword)
                                    .addComponent(lblSearchBy))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtKeyword)
                                    .addComponent(btnCourseNumber))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCourseName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(btnInstructor)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseRegistration)
                    .addComponent(btnBack))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSearchBy)
                        .addGap(20, 20, 20)
                        .addComponent(lblKeyword))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCourseNumber)
                            .addComponent(btnCourseName)
                            .addComponent(btnInstructor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch))))
                .addGap(45, 45, 45)
                .addComponent(lblCourseOffer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEnroll)
                        .addGap(64, 64, 64)))
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(btnDrop)
                        .addGap(111, 111, 111))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCourseNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseNumberActionPerformed
        searchType = "CourseNumber";
    }//GEN-LAST:event_btnCourseNumberActionPerformed

    private void btnCourseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseNameActionPerformed
        searchType = "CourseName";
    }//GEN-LAST:event_btnCourseNameActionPerformed

    private void btnInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstructorActionPerformed
        searchType = "Instructor";
    }//GEN-LAST:event_btnInstructorActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String keyword = txtKeyword.getText();
        ArrayList<CourseOffer> resultList = new ArrayList<>();

        for (CourseOffer c : department.getAllCourseOffers()) {
            String courseNumber = c.getCourseNumber();
            String courseName = c.getSubjectCourse().getCourseName();
            String instructor = getInstructorByCourseNumber(courseNumber);

            if (searchType.equals("CourseNumber") && courseNumber.toLowerCase().contains(keyword.toLowerCase())) {
                resultList.add(c);
            } else if (searchType.equals("CourseName") && courseName.toLowerCase().contains(keyword.toLowerCase())) {
                resultList.add(c);
            } else if (searchType.equals("Instructor") && instructor.toLowerCase().contains(keyword.toLowerCase())) {
                resultList.add(c);
            }
        }

        populateAvailableCoursesTable(resultList);

        if (resultList.isEmpty() && !keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No courses found for: " + keyword);
        }               
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollActionPerformed
        int selectedRow = tblCourseOffer.getSelectedRow();
    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this, "Please select a course to enroll!");
        return;
    }

    // 现在第0列是课程编号，第1列是课程名称
    String courseNumber = (String) tblCourseOffer.getValueAt(selectedRow, 0);
    int credits = (Integer) tblCourseOffer.getValueAt(selectedRow, 3);

    // 检查是否已经注册过这门课（用课程编号比较）
    DefaultTableModel registeredModel = (DefaultTableModel) tblRegisteredCourse.getModel();
    for (int i = 0; i < registeredModel.getRowCount(); i++) {
        String registeredCourseNumber = (String) registeredModel.getValueAt(i, 0);
        if (registeredCourseNumber.equals(courseNumber)) {
            JOptionPane.showMessageDialog(this, "You already have this course!");
            return;
        }
    }

    // 重新计算总学分（添加调试信息）
    int totalCredits = calculateTotalCredits();
    System.out.println("当前总学分: " + totalCredits); // 调试用
    System.out.println("要添加的学分: " + credits);    // 调试用
    
    if (totalCredits + credits > 8) {
        JOptionPane.showMessageDialog(this, 
            "You cannot exceed 8 credits! Current credits: " + totalCredits + 
            ", New course credits: " + credits);
        return;
    }

    // 添加到表格
    Object[] row = {
        courseNumber,                                    // 课程编号
        tblCourseOffer.getValueAt(selectedRow, 1),      // 课程名称
        tblCourseOffer.getValueAt(selectedRow, 2),      // 教师
        credits                                          // 学分
    };
    registeredModel.addRow(row);

    // 添加到学生的注册列表
    for (CourseOffer co : department.getAllCourseOffers()) {
        if (co.getCourseNumber().equals(courseNumber)) {
            studentProfile.registerCourseOffer(co);
            System.out.println("成功注册课程: " + courseNumber); // 调试用
            break;
        }
    }

    JOptionPane.showMessageDialog(this, "Successfully enrolled in " + courseNumber + "!");

    }//GEN-LAST:event_btnEnrollActionPerformed

    private void btnDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDropActionPerformed
    int selectedRow = tblRegisteredCourse.getSelectedRow();
    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this, "Please select a course to drop!");
        return;
    }

    // 现在第0列是课程编号
    String courseNumber = (String) tblRegisteredCourse.getValueAt(selectedRow, 0);
    
    // 从表格删除
    DefaultTableModel model = (DefaultTableModel) tblRegisteredCourse.getModel();
    model.removeRow(selectedRow);

    // 从学生注册列表删除
    ArrayList<CourseOffer> courses = studentProfile.getRegisteredCourseOffers();
    if (courses != null) {
        courses.removeIf(c -> c.getCourseNumber().equals(courseNumber));
        System.out.println("退课后剩余课程数: " + courses.size()); // 调试用
        System.out.println("退课后总学分: " + calculateTotalCredits()); // 调试用
    }

    JOptionPane.showMessageDialog(this, "You have dropped " + courseNumber + ".");
    }//GEN-LAST:event_btnDropActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    userProcessContainer.remove(this);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCourseName;
    private javax.swing.JButton btnCourseNumber;
    private javax.swing.JButton btnDrop;
    private javax.swing.JButton btnEnroll;
    private javax.swing.JButton btnInstructor;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCourseOffer;
    private javax.swing.JLabel lblCourseRegistration;
    private javax.swing.JLabel lblKeyword;
    private javax.swing.JLabel lblSearchBy;
    private javax.swing.JTable tblCourseOffer;
    private javax.swing.JTable tblRegisteredCourse;
    private javax.swing.JTextField txtKeyword;
    // End of variables declaration//GEN-END:variables
}
