/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package UserInterface.WorkAreas.StudentRole;

import University.Business;
import University.Department.Department;
import University.Persona.Student.StudentProfile;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author kal
 */
public class StudentWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Business business;
    private StudentProfile student;
    private Department department;

    public StudentWorkAreaJPanel(JPanel upc, Business b, StudentProfile sp, Department d) {
        this.userProcessContainer = upc;
        this.business = b;
        this.student = sp;
        this.department = d;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCourseWorkManagement = new javax.swing.JButton();
        btnProfileManagement = new javax.swing.JButton();
        btnGraduationAudit = new javax.swing.JButton();
        btnCourseRegistration = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnTranscriptReview = new javax.swing.JButton();
        btnFinancialManagement = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(new java.awt.Color(51, 51, 51));

        btnCourseWorkManagement.setBackground(new java.awt.Color(102, 0, 102));
        btnCourseWorkManagement.setFont(getFont());
        btnCourseWorkManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnCourseWorkManagement.setText("Coursework Management");
        btnCourseWorkManagement.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCourseWorkManagement.setMaximumSize(new java.awt.Dimension(200, 40));
        btnCourseWorkManagement.setMinimumSize(new java.awt.Dimension(20, 23));
        btnCourseWorkManagement.setPreferredSize(new java.awt.Dimension(240, 30));
        btnCourseWorkManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseWorkManagementIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnProfileManagement.setBackground(new java.awt.Color(204, 102, 0));
        btnProfileManagement.setFont(getFont());
        btnProfileManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnProfileManagement.setText("Profile Management");
        btnProfileManagement.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProfileManagement.setMaximumSize(new java.awt.Dimension(200, 40));
        btnProfileManagement.setMinimumSize(new java.awt.Dimension(20, 20));
        btnProfileManagement.setPreferredSize(new java.awt.Dimension(240, 25));
        btnProfileManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileManagementActionPerformed(evt);
            }
        });

        btnGraduationAudit.setBackground(new java.awt.Color(0, 102, 0));
        btnGraduationAudit.setFont(getFont());
        btnGraduationAudit.setForeground(new java.awt.Color(255, 255, 255));
        btnGraduationAudit.setText("Graduation Audit");
        btnGraduationAudit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGraduationAudit.setMaximumSize(new java.awt.Dimension(200, 40));
        btnGraduationAudit.setMinimumSize(new java.awt.Dimension(20, 20));
        btnGraduationAudit.setPreferredSize(new java.awt.Dimension(240, 25));
        btnGraduationAudit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraduationAuditActionPerformed(evt);
            }
        });

        btnCourseRegistration.setBackground(new java.awt.Color(153, 0, 0));
        btnCourseRegistration.setFont(getFont());
        btnCourseRegistration.setForeground(new java.awt.Color(255, 255, 255));
        btnCourseRegistration.setText("Course Registration");
        btnCourseRegistration.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCourseRegistration.setMaximumSize(new java.awt.Dimension(200, 40));
        btnCourseRegistration.setMinimumSize(new java.awt.Dimension(20, 20));
        btnCourseRegistration.setPreferredSize(new java.awt.Dimension(240, 25));
        btnCourseRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseRegistrationActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitle.setText("My Student Portal");

        btnTranscriptReview.setBackground(new java.awt.Color(102, 102, 102));
        btnTranscriptReview.setFont(getFont());
        btnTranscriptReview.setForeground(new java.awt.Color(255, 255, 255));
        btnTranscriptReview.setText("Transcript Review");
        btnTranscriptReview.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTranscriptReview.setMaximumSize(new java.awt.Dimension(200, 40));
        btnTranscriptReview.setMinimumSize(new java.awt.Dimension(20, 20));
        btnTranscriptReview.setPreferredSize(new java.awt.Dimension(240, 25));
        btnTranscriptReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranscriptReviewActionPerformed(evt);
            }
        });

        btnFinancialManagement.setBackground(new java.awt.Color(0, 51, 153));
        btnFinancialManagement.setFont(getFont());
        btnFinancialManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnFinancialManagement.setText("Financial Management");
        btnFinancialManagement.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFinancialManagement.setMaximumSize(new java.awt.Dimension(200, 40));
        btnFinancialManagement.setMinimumSize(new java.awt.Dimension(20, 20));
        btnFinancialManagement.setPreferredSize(new java.awt.Dimension(240, 25));
        btnFinancialManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinancialManagementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnTranscriptReview, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(btnProfileManagement, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(btnCourseWorkManagement, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnGraduationAudit, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(btnCourseRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(btnFinancialManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(218, 218, 218))
            .addGroup(layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblTitle)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCourseWorkManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCourseRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProfileManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGraduationAudit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTranscriptReview, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFinancialManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCourseWorkManagementIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseWorkManagementIdentifyResourceAssetsActionPerformed
    StudentProfile s1 = business.getDefaultStudent();
    CourseWorkManagementJPanel panel = new CourseWorkManagementJPanel(userProcessContainer,business,s1);
    userProcessContainer.add("CourseWorkManagementJPanel", panel);
    CardLayout layout = (CardLayout)userProcessContainer.getLayout();
    layout.show(userProcessContainer,"CourseWorkManagementJPanel");
    }//GEN-LAST:event_btnCourseWorkManagementIdentifyResourceAssetsActionPerformed

    private void btnProfileManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileManagementActionPerformed
        ProfileManagementJPanel panel = new ProfileManagementJPanel(userProcessContainer,student);
        userProcessContainer.add("ProfileManagementJPanel", panel);
        CardLayout layout =(CardLayout)userProcessContainer.getLayout();
        layout.show(userProcessContainer,"ProfileManagementJPanel");
}//GEN-LAST:event_btnProfileManagementActionPerformed

    private void btnGraduationAuditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraduationAuditActionPerformed
        GraduationAuditJPanel panel = new GraduationAuditJPanel(userProcessContainer, business, student);
        userProcessContainer.add("GraduationAuditJPanel", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.show(userProcessContainer,"GraduationAuditJPanel");
    }//GEN-LAST:event_btnGraduationAuditActionPerformed

    private void btnCourseRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseRegistrationActionPerformed
        CourseRegistrationJPanel panel = new CourseRegistrationJPanel(userProcessContainer, student, department);
        userProcessContainer.add("CourseRegistrationJPanel", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.show(userProcessContainer,"CourseRegistrationJPanel");
}//GEN-LAST:event_btnCourseRegistrationActionPerformed

    private void btnTranscriptReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranscriptReviewActionPerformed
        TranscriptReviewJPanel panel = new TranscriptReviewJPanel(userProcessContainer, student);
        userProcessContainer.add("TranscriptReviewJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.show(userProcessContainer,"TranscriptReviewJPanel");
    }//GEN-LAST:event_btnTranscriptReviewActionPerformed

    private void btnFinancialManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinancialManagementActionPerformed
        FinancialManagementJPanel panel = new FinancialManagementJPanel(userProcessContainer, student);
        userProcessContainer.add("FinancialManagementJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.show(userProcessContainer,"FinancialManagementJPanel");
    }//GEN-LAST:event_btnFinancialManagementActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourseRegistration;
    private javax.swing.JButton btnCourseWorkManagement;
    private javax.swing.JButton btnFinancialManagement;
    private javax.swing.JButton btnGraduationAudit;
    private javax.swing.JButton btnProfileManagement;
    private javax.swing.JButton btnTranscriptReview;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

}
