/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package UserInterface.WorkAreas.AdminRole;

import University.Business;
import University.Department.Department;
import University.Persona.UserAccount;
import University.Persona.Employee.EmployeeProfile;
import UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp.ManageUserAccountsJPanel;
import UserInterface.WorkAreas.AdminRole.ManageRegistrar.ManageRegistrar;
import UserInterface.WorkAreas.AdminRole.ManageStudent.ManageStudentJPanel;
import UserInterface.WorkAreas.AdminRole.ManageTeacher.ManageTeacherJPanel;
import UserInterface.WorkAreas.AdminRole.MyProfile.MyProfileJPanel;
import UserInterface.WorkAreas.AdminRole.Dashboard.DashboardJPanel;
import UserInterface.WorkAreas.AdminRole.FacultyAssignment.FacultyAssignmentJPanel;
import UserInterface.WorkAreas.AdminRole.Dashboard.DashboardJPanel;
import UserInterface.WorkAreas.AdminRole.RegisterPerson.SignUpJPanel;


import javax.swing.JPanel;

/**
 *
 * @author kal
 */
public class AdminRoleWorkAreaJPanel extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;
    Department department;
    UserAccount useraccount;
    EmployeeProfile employee;

    /**
     * Creates new form UnitRiskWorkArea
     */

    public AdminRoleWorkAreaJPanel(Business b, Department d, JPanel clp, UserAccount ua, EmployeeProfile emp) {

        business = b;
        this.department = d;
        this.CardSequencePanel = clp;
        this.useraccount = ua;
        this.employee = emp;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUserAccount = new javax.swing.JButton();
        btnManageFaculty = new javax.swing.JButton();
        btnRegisterPerson = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnManageStudents = new javax.swing.JButton();
        btnDashBoard = new javax.swing.JButton();
        btnAssignFaculty = new javax.swing.JButton();
        btnManageRegistrar = new javax.swing.JButton();

        setForeground(new java.awt.Color(51, 51, 51));

        btnUserAccount.setBackground(new java.awt.Color(102, 153, 255));
        btnUserAccount.setFont(getFont());
        btnUserAccount.setForeground(new java.awt.Color(255, 255, 255));
        btnUserAccount.setText("Administer User Accounts");
        btnUserAccount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUserAccount.setMaximumSize(new java.awt.Dimension(200, 40));
        btnUserAccount.setMinimumSize(new java.awt.Dimension(20, 23));
        btnUserAccount.setPreferredSize(new java.awt.Dimension(240, 30));
        btnUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserAccountIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnManageFaculty.setBackground(new java.awt.Color(102, 153, 255));
        btnManageFaculty.setFont(getFont());
        btnManageFaculty.setForeground(new java.awt.Color(255, 255, 255));
        btnManageFaculty.setText("Manage Faculty");
        btnManageFaculty.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageFaculty.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageFaculty.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageFaculty.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFacultyActionPerformed(evt);
            }
        });

        btnRegisterPerson.setBackground(new java.awt.Color(102, 153, 255));
        btnRegisterPerson.setFont(getFont());
        btnRegisterPerson.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterPerson.setText("Register  Persons (HR)");
        btnRegisterPerson.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegisterPerson.setMaximumSize(new java.awt.Dimension(200, 40));
        btnRegisterPerson.setMinimumSize(new java.awt.Dimension(20, 20));
        btnRegisterPerson.setPreferredSize(new java.awt.Dimension(240, 25));
        btnRegisterPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterPersonActionPerformed(evt);
            }
        });

        btnProfile.setBackground(new java.awt.Color(102, 153, 255));
        btnProfile.setFont(getFont());
        btnProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnProfile.setText("My Profile");
        btnProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProfile.setMaximumSize(new java.awt.Dimension(145, 40));
        btnProfile.setMinimumSize(new java.awt.Dimension(20, 20));
        btnProfile.setPreferredSize(new java.awt.Dimension(240, 25));
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileIdentifyEventsActionPerformed(evt);
            }
        });

        btnManageStudents.setBackground(new java.awt.Color(102, 153, 255));
        btnManageStudents.setFont(getFont());
        btnManageStudents.setForeground(new java.awt.Color(255, 255, 255));
        btnManageStudents.setText("Manage Students");
        btnManageStudents.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageStudents.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageStudents.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageStudents.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStudentsActionPerformed(evt);
            }
        });

        btnDashBoard.setBackground(new java.awt.Color(102, 153, 255));
        btnDashBoard.setFont(getFont());
        btnDashBoard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashBoard.setText("Dashboard");
        btnDashBoard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDashBoard.setMaximumSize(new java.awt.Dimension(200, 40));
        btnDashBoard.setMinimumSize(new java.awt.Dimension(20, 20));
        btnDashBoard.setPreferredSize(new java.awt.Dimension(240, 25));
        btnDashBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashBoardActionPerformed(evt);
            }
        });

        btnAssignFaculty.setBackground(new java.awt.Color(102, 153, 255));
        btnAssignFaculty.setFont(getFont());
        btnAssignFaculty.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignFaculty.setText("Assign Faculty");
        btnAssignFaculty.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAssignFaculty.setMaximumSize(new java.awt.Dimension(200, 40));
        btnAssignFaculty.setMinimumSize(new java.awt.Dimension(20, 20));
        btnAssignFaculty.setPreferredSize(new java.awt.Dimension(240, 25));
        btnAssignFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignFacultyActionPerformed(evt);
            }
        });

        btnManageRegistrar.setBackground(new java.awt.Color(102, 153, 255));
        btnManageRegistrar.setFont(getFont());
        btnManageRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnManageRegistrar.setText("Manage Registrar");
        btnManageRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageRegistrar.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageRegistrar.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageRegistrar.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnManageFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUserAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegisterPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAssignFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegisterPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUserAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAssignFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserAccountIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserAccountIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:

//        // Remove existing panel if it exists
//        for (int i = 0; i < CardSequencePanel.getComponentCount(); i++) {
//            if (CardSequencePanel.getComponent(i).getName() != null && 
//                CardSequencePanel.getComponent(i).getName().equals("ManageVulns")) {
//                CardSequencePanel.remove(i);
//                break;
//            }
//        }
        
        ManageUserAccountsJPanel aos = new ManageUserAccountsJPanel(business, CardSequencePanel);
        aos.setName("ManageVulns");
        CardSequencePanel.add("ManageVulns", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "ManageVulns");

    }//GEN-LAST:event_btnUserAccountIdentifyResourceAssetsActionPerformed

    private void btnRegisterPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterPersonActionPerformed
        // TODO add your handling code here:
        
//        // Remove existing panel if it exists
//        for (int i = 0; i < CardSequencePanel.getComponentCount(); i++) {
//            if (CardSequencePanel.getComponent(i).getName() != null && 
//                CardSequencePanel.getComponent(i).getName().equals("Manage Persons")) {
//                CardSequencePanel.remove(i);
//                break;
//            }
//        }
        
        SignUpJPanel aos = new SignUpJPanel(business, CardSequencePanel);
        aos.setName("Manage Persons");
        CardSequencePanel.add("Manage Persons", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "Manage Persons");

    }//GEN-LAST:event_btnRegisterPersonActionPerformed

    private void btnManageStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStudentsActionPerformed
        // TODO add your handling code here:
        
//        // Remove existing panel if it exists
//        for (int i = 0; i < CardSequencePanel.getComponentCount(); i++) {
//            if (CardSequencePanel.getComponent(i).getName() != null && 
//                CardSequencePanel.getComponent(i).getName().equals("Manage Students")) {
//                CardSequencePanel.remove(i);
//                break;
//            }
//        }
        
        ManageStudentJPanel aos = new ManageStudentJPanel(CardSequencePanel, business.getStudentDirectory());
        aos.setName("Manage Students");
        CardSequencePanel.add("Manage Students", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "Manage Students");


    }//GEN-LAST:event_btnManageStudentsActionPerformed

    private void btnProfileIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileIdentifyEventsActionPerformed
        
//        // Remove existing panel if it exists
//        for (int i = 0; i < CardSequencePanel.getComponentCount(); i++) {
//            if (CardSequencePanel.getComponent(i).getName() != null && 
//                CardSequencePanel.getComponent(i).getName().equals("View Profile")) {
//                CardSequencePanel.remove(i);
//                break;
//            }
//        }
        
        MyProfileJPanel aos = new MyProfileJPanel(CardSequencePanel, useraccount, employee);
        aos.setName("View Profile");
        CardSequencePanel.add("View Profile", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "View Profile");
    }//GEN-LAST:event_btnProfileIdentifyEventsActionPerformed

    private void btnManageFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFacultyActionPerformed
    
//        // Remove existing panel if it exists
//        for (int i = 0; i < CardSequencePanel.getComponentCount(); i++) {
//            if (CardSequencePanel.getComponent(i).getName() != null && 
//                CardSequencePanel.getComponent(i).getName().equals("Manage Teachers")) {
//                CardSequencePanel.remove(i);
//                break;
//            }
//        }
    
        ManageTeacherJPanel aos = new ManageTeacherJPanel(CardSequencePanel, business.getFacultyDirectoryFromDepartment(), null);
        aos.setName("Manage Teachers");
        CardSequencePanel.add("Manage Teachers", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "Manage Teachers");

    }//GEN-LAST:event_btnManageFacultyActionPerformed
                                    

    private void btnAssignFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignFacultyActionPerformed
        // TODO add your handling code here:
        
//        // Remove existing panel if it exists
//        for (int i = 0; i < CardSequencePanel.getComponentCount(); i++) {
//            if (CardSequencePanel.getComponent(i).getName() != null && 
//                CardSequencePanel.getComponent(i).getName().equals("Manage Registrar")) {
//                CardSequencePanel.remove(i);
//                break;
//            }
//        }
         FacultyAssignmentJPanel assignmentPanel = new FacultyAssignmentJPanel(business, department, CardSequencePanel);
        assignmentPanel.setName("Faculty Assignment");
        CardSequencePanel.add("Faculty Assignment", assignmentPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "Faculty Assignment");
       

    }//GEN-LAST:event_btnAssignFacultyActionPerformed

    private void btnDashBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashBoardActionPerformed
        // TODO add your handling code here:

        // Remove existing panel if it exists
//        for (int i = 0; i < CardSequencePanel.getComponentCount(); i++) {
//            if (CardSequencePanel.getComponent(i).getName() != null && 
//                CardSequencePanel.getComponent(i).getName().equals("Analytics Dashboard")) {
//                CardSequencePanel.remove(i);
//                break;
//            }
//        }

        DashboardJPanel dashboard = new DashboardJPanel(business, department, CardSequencePanel);
        dashboard.setName("Analytics Dashboard");

 
        CardSequencePanel.add("Analytics Dashboard", dashboard);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "Analytics Dashboard");
    }//GEN-LAST:event_btnDashBoardActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
//        
//        // Remove existing panel if it exists
//        for (int i = 0; i < CardSequencePanel.getComponentCount(); i++) {
//            if (CardSequencePanel.getComponent(i).getName() != null && 
//                CardSequencePanel.getComponent(i).getName().equals("Faculty Assignment")) {
//                CardSequencePanel.remove(i);
//                break;
//            }
//        }
        
        FacultyAssignmentJPanel assignmentPanel = new FacultyAssignmentJPanel(business, department, CardSequencePanel);
        assignmentPanel.setName("Faculty Assignment");
        CardSequencePanel.add("Faculty Assignment", assignmentPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "Faculty Assignment");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void btnManageRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRegistrarActionPerformed
        // TODO add your handling code here:
         ManageRegistrar aos = new ManageRegistrar(business, CardSequencePanel);
        aos.setName("Manage Registrar");
        CardSequencePanel.add("Manage Registrar", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "Manage Registrar");
    }//GEN-LAST:event_btnManageRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignFaculty;
    private javax.swing.JButton btnDashBoard;
    private javax.swing.JButton btnManageFaculty;
    private javax.swing.JButton btnManageRegistrar;
    private javax.swing.JButton btnManageStudents;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnRegisterPerson;
    private javax.swing.JButton btnUserAccount;
    // End of variables declaration//GEN-END:variables

}
