/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.AdminRole.FacultyAssignment;

import University.Business;
import University.CourseSchedule.CourseOffer;
import University.CourseSchedule.CourseSchedule;
import University.Department.Department;
import University.Persona.Faculty.FacultyDirectory;
import University.Persona.Faculty.FacultyProfile;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class FacultyAssignmentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FacultyAssignmentJPanel
     */
    
    private JPanel CardSequencePanel;
    private Business business;
    private Department department;
    private FacultyDirectory facultyDirectory;
    public FacultyAssignmentJPanel(Business b, Department d, JPanel clp) {
        initComponents();
        this.business = b;
        this.department = d;
        this.CardSequencePanel = clp;
        this.facultyDirectory = d.getFacultyDirectory();
        populateSemesters();
        initTables();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourse = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAssignment = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSemester = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnAssign = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setForeground(new java.awt.Color(242, 242, 242));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel1.setText("Faculty Course Assignment Management");

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel2.setText("Available Course");

        tblCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course ID", "Name", "Credits", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCourse);

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel3.setText("Current Assignment");

        tblAssignment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Name", "Faculty ID", "Faculty Name", "Semester"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblAssignment);

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel4.setText("Faculty");

        tblSemester.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Faculty ID", "Faculty Name", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblSemester);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        btnAssign.setText("Assign Faculty to Course");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove Assignment");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(116, 116, 116)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(89, 89, 89)
                                                .addComponent(btnRefresh))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(65, 65, 65)
                                                .addComponent(btnBack))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel4)
                                                .addGap(149, 149, 149))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(125, 125, 125)
                                        .addComponent(jLabel3)))
                                .addGap(30, 30, 30)))
                        .addContainerGap(8, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAssign)
                        .addGap(46, 46, 46)
                        .addComponent(btnRemove))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(340, 340, 340))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
           refreshTables();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        
        
          int facultyRow = tblSemester.getSelectedRow();
        int courseRow = tblCourse.getSelectedRow();
        
        if (facultyRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a faculty member", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (courseRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a course", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String facultyId = (String) tblSemester.getValueAt(facultyRow, 0);
        String courseId = (String) tblCourse.getValueAt(courseRow, 0);
        String semester = (String) jComboBox1.getSelectedItem();
        
        // Find faculty and course
        FacultyProfile faculty = facultyDirectory.findTeachingFaculty(facultyId);
        CourseSchedule courseSchedule = department.getCourseSchedule(semester);
        
        if (faculty == null) {
            JOptionPane.showMessageDialog(this, "Faculty not found", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (courseSchedule == null) {
            JOptionPane.showMessageDialog(this, "Course schedule not found for semester: " + semester, "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        CourseOffer courseOffer = courseSchedule.getCourseOfferByNumber(courseId);
        if (courseOffer == null) {
            JOptionPane.showMessageDialog(this, "Course offer not found", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Check if already assigned
        if (courseOffer.getFacultyProfile() != null) {
            int result = JOptionPane.showConfirmDialog(this, 
                "This course is already assigned to " + courseOffer.getFacultyProfile().getPerson().getName() + 
                ". Do you want to reassign?", "Reassign Faculty", JOptionPane.YES_NO_OPTION);
            if (result != JOptionPane.YES_OPTION) {
                return;
            }
        }
        
        // Assign faculty to course
        courseOffer.AssignAsTeacher(faculty);
        faculty.assignAsTeacher(courseOffer);
        
        JOptionPane.showMessageDialog(this, "Faculty assigned successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        refreshTables();
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        
        int assignmentRow = tblAssignment.getSelectedRow();
        
        if (assignmentRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an assignment to remove", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String courseId = (String) tblAssignment.getValueAt(assignmentRow, 0);
        String courseName = (String) tblAssignment.getValueAt(assignmentRow, 1);
        String facultyId = (String) tblAssignment.getValueAt(assignmentRow, 2);
        String facultyName = (String) tblAssignment.getValueAt(assignmentRow, 3);
        String semester = (String) tblAssignment.getValueAt(assignmentRow, 4);
        
        int result = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to remove this assignment?", "Confirm Removal", JOptionPane.YES_NO_OPTION);
        
        if (result == JOptionPane.YES_OPTION) {
            // Find and remove assignment
            CourseSchedule courseSchedule = department.getCourseSchedule(semester);
            if (courseSchedule != null) {
                for (CourseOffer co : courseSchedule.getCourseOfferList()) {
                    if (co.getCourseNumber().equals(courseId) && co.getCourseName().equals(courseName) && co.getFacultyProfile() != null && 
                        co.getFacultyProfile().getPerson().getUniversityID().equals(facultyId)) {
                        // 清除教师分配
                        co.setFacultyassignment(null);
                        break;
                    }
                }
            }
            
            JOptionPane.showMessageDialog(this, "Assignment removed successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            refreshTables();
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         CardSequencePanel.remove(this);
        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
        layout.previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
         refreshTables();
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblAssignment;
    private javax.swing.JTable tblCourse;
    private javax.swing.JTable tblSemester;
    // End of variables declaration//GEN-END:variables

   private void initTables() {
        refreshTables();
    }
    
    private void refreshTables() {
        refreshFacultyTable();
        refreshCourseTable();
        refreshAssignmentTable();
    }
    
    private void refreshFacultyTable() {
        DefaultTableModel model = (DefaultTableModel) tblSemester.getModel();
        model.setRowCount(0);
        
        String semester = (String) jComboBox1.getSelectedItem();
        java.util.Set<String> assignedFacultyIds = new java.util.HashSet<>();
        if (semester != null) {
            CourseSchedule cs = department.getCourseSchedule(semester);
            if (cs != null) {
                for (CourseOffer co : cs.getCourseOfferList()) {
                    if (co.getFacultyProfile() != null) {
                        assignedFacultyIds.add(co.getFacultyProfile().getPerson().getUniversityID());
                    }
                }
            }
        }

        if (facultyDirectory != null && facultyDirectory.getTeacherlist() != null) {
            for (FacultyProfile faculty : facultyDirectory.getTeacherlist()) {
                if (faculty != null && faculty.getPerson() != null) {
                    Object[] row = new Object[3];
                    row[0] = faculty.getPerson().getUniversityID();
                    row[1] = faculty.getPerson().getName();
                    row[2] = assignedFacultyIds.contains(faculty.getPerson().getUniversityID()) ? "Assigned" : "Available";
                    model.addRow(row);
                }
            }
        }
    }
    
    private void refreshCourseTable() {
        DefaultTableModel model = (DefaultTableModel) tblCourse.getModel();
        model.setRowCount(0);
        
        String semester = (String) jComboBox1.getSelectedItem();
        CourseSchedule courseSchedule = department.getCourseSchedule(semester);
        
        if (courseSchedule != null && courseSchedule.getCourseOfferList() != null) {
            for (CourseOffer courseOffer : courseSchedule.getCourseOfferList()) {
                if (courseOffer != null && courseOffer.getCourse() != null) {
                    Object[] row = new Object[4];
                    row[0] = courseOffer.getCourseNumber();
                    row[1] = courseOffer.getCourseName();
                    row[2] = courseOffer.getCourse().getCredits();
                    row[3] = courseOffer.getFacultyProfile() != null ? 
                        ("Assigned ") : "Unassigned";
                    model.addRow(row);
                }
            }
        }
    }
    
    private void refreshAssignmentTable() {
        DefaultTableModel model = (DefaultTableModel) tblAssignment.getModel();
        model.setRowCount(0);
        
        String semester = (String) jComboBox1.getSelectedItem();
        CourseSchedule courseSchedule = department.getCourseSchedule(semester);
        
        if (courseSchedule != null && courseSchedule.getCourseOfferList() != null) {
            for (CourseOffer courseOffer : courseSchedule.getCourseOfferList()) {
                if (courseOffer != null && courseOffer.getFacultyProfile() != null) {
                    Object[] row = new Object[5];
                    row[0] = courseOffer.getCourseNumber();
                    row[1] = courseOffer.getCourseName();
                    row[2] = courseOffer.getFacultyProfile().getPerson().getUniversityID();
                    row[3] = courseOffer.getFacultyProfile().getPerson().getName();
                    row[4] = semester;
                    model.addRow(row);
                }
            }
        }
    }

    private void populateSemesters() {
        jComboBox1.removeAllItems();
        java.util.Set<String> semesters = department.getAllSemesters();
        if (semesters != null && !semesters.isEmpty()) {
            for (String s : semesters) {
                jComboBox1.addItem(s);
            }
            jComboBox1.setSelectedIndex(0);
        }
    }
}
